
export const PRODUCT_LIST = "PRODUCT_LIST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_ERR = "PRODUCT_LIST_ERR"

export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const CREATE_PRODUCT_ERR = "CREATE_PRODUCT_ERR"

export const CART_ITEMS_LIST = "CART_ITEMS_LIST";
export const CART_ITEMS_LIST_SUCCESS = "CART_ITEMS_LIST_SUCCESS";
export const CART_ITEMS_LIST_ERR = "CART_ITEMS_LIST_ERR";

export const ADD_CART = "ADD_CART";
export const ADD_CART_SUCCESS = "ADD_CART_SUCCESS";
export const ADD_CART_ERR = "ADD_CART_ERR";

export const UPDATE_CART_QUANTITY = "UPDATE_CART_QUANTITY";
export const UPDATE_CART_QUANTITY_SUCCESS = "UPDATE_CART_QUANTITY_SUCCESS"
